config/routes.rb
Rails.application.routes.draw do



# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
    resources :posts, only: [:index, :new]
  end
  resources :posts, except: [:index, :new]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord


  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :xposts,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

  has_many :subs,
    through: :xposts,
    source: :sub

  
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint           not null, primary key
#  post_id    :integer
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord

  belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post,
    inverse_of: :xposts

  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub,
    inverse_of: :postscrossed

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :postscrossed,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :postscrossed,
    source: :post



end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :password, length: {minimum:6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :subs_moderated,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post


  def self.find_by_credentials(password, username)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil 
  end


  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password=password
    self.password_digest=BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    return self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  #C R L L L

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    redirect_to new_session_url unless current_user
  end

  # def valid_login?
  #   logged_in?
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author, only:[:edit, :update]

  
  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    # @post.sub_id = params[:post][:sub_id]
    debugger
    if @post.save!
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author
      @post = Post.find(params[:id])
      render json: "Forbidden" if current_user.id != @post.author_id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:password],
      params[:user][:username]
    )
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to subs_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only:[:edit, :update]
 
  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub=Sub.find(params[:id])
    render :show
  end

  def new
    @sub=Sub.new
    render :new
  end

  def create
    @sub=Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save!
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub=Sub.find(params[:id])
    render :edit
  end

  def update
    @sub=Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title,:description)
  end

  def require_moderator
      @sub = Sub.find(params[:id])
      render json: "Forbidden" if current_user.id != @sub.moderator_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors]=@user.errors.full_messages
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% if logged_in? %>
    <ul>
      <li><%= current_user.username %></li>
      <li><a href="<%= new_sub_url %>">Create a sub!</a></li>
      <li><a href="<%= subs_url %>">All Subs</a></li>
      <li>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <button type="submit">Logout</button>
        </form>
      </li>
    </ul>
  <% else %>
     <a href="<%= new_session_url %>">Sign in!</a>
  <% end %>
  <% flash[:errors] if flash[:errors]  %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<main>
  
<% if type == :edit %>
  <h1>Edit Post!</h1>
  <% action = post_url(post) %>
  <% title = post.title%>
  <% url = post.url%>
  <% content = post.content%>
<% else %>
<h1>New Post!</h1>
  <% action = posts_url %>
  <% title = @post.title%>
  <% url = @post.url%>
  <% content = @post.content%>
<% end %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  

  <label>Title
    <input type="text" name="post[title]" value="<%= title %>" id = "title">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= url %>" id = "url">
  </label>

  <label>Content
    <textarea name="post[content]" id="content" cols="30" rows="10"><%= content %></textarea>
  </label>

  <label>Subs</label>

  <input type="hidden" name='post[sub_ids][]' value="">
<% debugger%>
  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %> 
        />
    </label>
  <% end %>
  <input type="submit" value="Submit!">

  </form>
</main>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form', type: :edit, post: @post %>

app/views/posts/new.html.erb
<%= render 'form', type: :new, sub_id: params[:sub_id] %>

app/views/posts/show.html.erb
<main>
  <h1><%= @post.title %> by <%= @post.author.username %></h1>

  <div>
    <label>Content:
      <p><%= @post.content %></p>
    </label>
  </div>

  <a href="<%= edit_post_url(@post) %>">Edit</a>
</main>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/_form.html.erb
<main>
  
<% if type == :edit %>
  <h1>Edit your Sub</h1>
  <% action = sub_url %>
<% else %>
<h1>create a sub</h1>
  <% action = subs_url %>
<% end %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>Name
    <input type="text" name="sub[title]" value="<%= sub.title %>" id = "name">
  </label>

  <label>Description
    <textarea name="sub[description]" id="description" cols="30" rows="10"><%= sub.description %></textarea>
  </label>
  <input type="submit" value="Submit!">

</form>
</main>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

<%= render 'form', type: :edit, sub: @sub%>

app/views/subs/index.html.erb
<main>
<h1>Subs#index</h1>
<ul>
  <% @subs.each do |sub|%>
    <li>
      <a href="<%= sub_url(sub.id)%>"><%=sub.title%></a>
    </li>
  <%end%>
</ul>
</main>

app/views/subs/new.html.erb
<%= render 'form', type: :create, sub: @sub%>

app/views/subs/show.html.erb
<main>
<h1><%= @sub.title %></h1>
<h2>Description</h2>
<h3><%= @sub.description %></h3>

<a href="<%= new_sub_post_url(@sub) %>">Make New Post!</a>
</main>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>" id = "username">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>"  id="password">
  </label>

  <button type="submit">create user</button>
</form>